doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        dbname_suffix: '_%kernel.environment%'

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
