rest_v1_raffle:
    resource:
        path: ../src/RaffleDemo/Raffle/UserInterface/Rest/V1/
        namespace: App\RaffleDemo\Raffle\UserInterface\Rest\V1
    type: attribute
    condition: "request.headers.get('Content-Type') === 'application/json'"
    stateless: true
    defaults:
        _format: json
